#!/usr/bin/env bash

TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-}"
TELEGRAM_CI_GROUP="LuminaireCI"
TELEGRAM_GROUP="LuminaireLab"

TELEGRAM_THREAD_ID_EVENT="4"

declare -A TELEGRAM_THREAD_ID_BUILD_BY_VERSION=(
    ["5.10"]="605"
    ["5.15"]="606"
    ["6.1"]="626"
    ["6.6"]="751"
    ["6.12"]="755"
)

TELEGRAM_THREAD_ID_RELEASE="84"

TELEGRAM_CHANNEL_ID="${TELEGRAM_CHANNEL_ID:-}"
